### ISSUE TITLE
Network socket is disabled when I close my laptop.

### ISSUE THREAD

**Issue by Seren541** [mgord9518/aisap#1]
I'm using AISAP to launch the Google Chrome AppImage made by using pkg2appimage. When I close my laptop screen and re-open it, Chrome no longer has internet. This can be fixed if I set the Level permission to 1 instead of 2.

**Comment by mgord9518** [comment]
What OS+DE are you running?

**Comment by mgord9518** [comment]
I was able to recreate this in the past but I can't manage to now, maybe try '--add-file /etc' and see if that fixes it, I assume it's some sort of system wakeup config that the level 2 sandbox isn't getting. If /etc doesn't work, try adding /sys instead

The difference between level 1 and 2 is full access to /dev, /etc, /sys and /usr, so one of those definitely has the file(s) which fixes this issue

**Comment by Seren541** [comment]
Do you have documentation on how to manage permissions using aisap? I get the gist, but I don't know how to add /etc using it at the moment.

**Comment by mgord9518** [comment]
Yeah there is documentation for it (in README.md) but it's easy to miss. In order to add a file or directory to the sandbox using the CLI tool, use the '--add-file' flag. Eg: '--add-file /etc' will give access to /etc.

**Comment by Seren541** [comment]
How can you reproduce this in ini format (that's the format I use to store permissions).

**Comment by mgord9518** [comment]
For the INI profiles, you can use the following flags for setting permissions:

Level
Files
Sockets
Devices

Provided they're all set under the [X-App Permissions] section. You can also add multiple elements if they're separated with a semicolon

In 'example/profile.ini' there's a sample profile that can be used as a reference, I'll throw a link to it in the main README.md to make it easier to find for the future though

**Comment by Seren541** [comment]
I don't know why but this error no longer seems to be a problem despite using the same version. I might have upgraded from 6.4 to 6.6 though so if you fixed something there that might have been the issue. Closing this issue unless it happens again.
