### ISSUE TITLE
hi , i want to build jriver media center for appimage, but it cannot work

### ISSUE THREAD

**Issue by newyorkthink** [mgord9518/aisap#10]
the jriver media center appimage always need /usr/lib/jriver folder exits
so, the aisap project can work and fixed it ?

**Comment by mgord9518** [comment]
I'm not really familiar with this application, are you developing an AppImage for it? AppImage's should only request files that are reasonably expected to be on a clean install, so if you're building it I would try to find out how to make that folder relative

**Comment by newyorkthink** [comment]
> I'm not really familiar with this application, are you developing an AppImage for it? AppImage's should only request files that are reasonably expected to be on a clean install, so if you're building it I would try to find out how to make that folder relative

Thank you

**Comment by mgord9518** [comment]
Yeah! I'd be happy to help if you have any issues, building portable AppImages can be difficult
