### ISSUE TITLE
ppsspp won't detect controller unless the `--add-device input` flag is given even though the database contains that already

### ISSUE THREAD

**Issue by Samueru-sama** [mgord9518/aisap#11]
Hi, I think it is better that I start splitting the issues instead of using the same one for everything.

-----------------------------------------------------------------

For some reason `ppsspp` will not pick up my xbox360 controller when it is sandboxed unless I explicitly pass the `--add-device input` flag, which I don't think it should be needed since ppsspp should have access to `"input"` by default as it is in the [database](https://github.com/mgord9518/aisap/blob/main/profiles/profile_database.json)?

Video: https://streamable.com/qebrgl

**Comment by mgord9518** [comment]
Can you send the ouput of `aisap -l [APPIMAGE]`? The latest version appears to be recognizing the input permission you added to the database but unfortunately it's tricky for me to actually test most AppImages nowadays since I'm on NixOS

I can't think of any reason it would be treating the flags differently since they're just appended to the existing permissions

**Comment by Samueru-sama** [comment]
> Can you send the ouput of `aisap -l [APPIMAGE]`? The latest version appears to be recognizing the input permission you added to the database but unfortunately it's tricky for me to actually test most AppImages nowadays since I'm on NixOS
> 
> I can't think of any reason it would be treating the flags differently since they're just appended to the existing permissions

You nailed it. 

```
aisap -l ./ppsspp
permissions:
  level:       3
  filesystem: []
  devices:    []
  sockets:    []

:: this app has no profile! falling back to default 
```

meanwhile with suyu it doesn't happen: 

```
aisap -l ./suyu
permissions:
  level:       2
  filesystem: [~/Downloads:ro, ~/Games:ro, ~/Roms:ro]
  devices:    [dri, input]
  sockets:    [x11, alsa, network]

:: sockets used by this app could be used to escape the sandbox 
```

**Comment by Samueru-sama** [comment]
I think the issue is very likely that the `.desktop` is called `PPSSPPSDL` instead of just `ppsspp`. 

I will test this in my fork and get back.

**Comment by mgord9518** [comment]
Oh yeah, I bet that's it. The PPSSPP AppImage I was testing is called ppsspp in the desktop entry name and had the permissions loaded correctly 

I'm gonna work on appstream support soon, hopefully using the app ID will be a bit more robust than the current system (assuming the AppImages have it and are using it correctly)
