### ISSUE TITLE
no access to USB flash drive

### ISSUE THREAD

**Issue by kinoegit** [mgord9518/aisap#14]
Hi @mgord9518 thank you for your good work! I like your interesting project very.
My issue: I've got a nitrokey to login to paypal but the chromium fork Thorium.AppImage doesn't get access to it.
Here is the relevant profile for Thorium:
```
[X-App Permissions]
Level=2
Files=~xdg-download:rw;
Devices=dri;input;
Sockets=x11;wayland;pulseaudio;network;
```
Running the AppImage without aisap it gets access to usb devices.
Is that feature not (yet) implemented or is it not intended?
Maybe I'm missing something?

**Comment by mgord9518** [comment]
Thanks for the report! It isn't yet implemented but I'd like to add support, unfortunately I don't have any of those devices so I can't directly test it

Do you happen to know the device file for your key? If so, you should be able to use the `--add-device` flag on the command line to enable it. If not, maybe try `--add-device usb`, which should work if the device is somewhere under /dev/usb

**Comment by mgord9518** [comment]
I'm just not very familiar with NitroKey and I'm not sure what it would take to get it functioning but as far as I know, all hardware devices on Linux should appear under dev, so try this:

*unplug USB key if in*

`find /dev > tmp`

*plug in USB key*

`find /dev > tmp2`

`diff tmp tmp2`

Hopefully you should only get a couple device files, try adding those to the sandbox and see if it works

**Comment by kinoegit** [comment]
No output to those commands (Arch Linux here)

**Comment by kinoegit** [comment]
Thats the output of `diff tmp tmp2`:

```
481a482,484
> /dev/char/189:9
> /dev/char/244:5
> /dev/char/180:97
493a497
> /dev/bus/usb/001/010
732a737
> /dev/usb/hiddev1
751a757
> /dev/hidraw5
```

**Comment by mgord9518** [comment]
Try using `--add-device char --add-device bus --add-device usb --add-device hidraw5` and see if it works

**Comment by kinoegit** [comment]
> Try using `--add-device char --add-device bus --add-device usb --add-device hidraw5` and see if it works

That didn't fix it. Thorium has no access to ANY of my usb drives despite of  `--add-device ...`

**Comment by mgord9518** [comment]
If you're also wondering about storage devices, you have to give access to wherever the media is mounted (typically `/run/media` or `/media` depending on distro). Example: `--add-file /run/media/USERNAME/DRIVE_NAME:rw` (append `:rw` for read-write permissions)

I'm not really sure about the NitroKey though, I've tried looking it up but I can't really find any info about how it works under Linux so I'm not sure what it needs access to in order to function

**Comment by Samueru-sama** [comment]
There is a nitrokey app on flathub which perms have access to all devices, I don't know if aisap has a flag like `--device=all` that does the same.

**Comment by kinoegit** [comment]
> If you're also wondering about storage devices, you have to give access to wherever the media is mounted (typically `/run/media` or `/media` depending on distro). Example: `--add-file /run/media/USERNAME/DRIVE_NAME:rw` (append `:rw` for read-write permissions)
> 
> I'm not really sure about the NitroKey though, I've tried looking it up but I can't really find any info about how it works under Linux so I'm not sure what it needs access to in order to function

OK thanks, I should have known. Anyway that does the trick for the storage usb drives.

**Comment by kinoegit** [comment]
@Samueru-sama 

> Edit: Also test using level 1 instead.

That does it! Thanks. Though running a browser with permission level 1 might be a security problem?

**Comment by Samueru-sama** [comment]
> That does it! Thanks. Though running a browser with permission level 1 might be a security problem?

https://github.com/mgord9518/aisap/blob/main/permissions/README.md

If level 1 works it means that some device is missing, I had this issue before with another app where using level 1 fixed it and then I just kept trying until I found what I was missing in level 2.

**Comment by kinoegit** [comment]
I suppose i should test with permission  `--dev-bind /dev   /dev`
How to in run command or profile.ini?

**Comment by Samueru-sama** [comment]
> I suppose i should test with permission `--dev-bind /dev /dev` How to in run command or profile.ini?

Try `--add-file /dev` not sure.

**Comment by mgord9518** [comment]
Yeah, level 1 isn't necessarily bad or insecure, but I believe applications should be sandboxed as heavily as possible while still remaining functional. The only differences between 1 and 2 are device and other basic system files, nothing that would allow sandbox escape, extra privileges or anything nasty. As far as using hardware keys, I think it might be a good enough reason to move web browsers to level 1

> I suppose i should test with permission `--dev-bind /dev /dev`
> How to in run command or profile.ini?

With the way things are currently set up, the only way to enable all devices is to lower the "base level" to 1 using `--level 1`. For using the profile, just change the `Level` key. Aisap should be simple to use, so unfortunately that requires losing some fine-grained control that you might get using bubblewrap directly.

**Comment by kinoegit** [comment]
Thanks a lot mgord9518 and Samueru-sama. I will run it with permission level 1. 
btw: tried to run with `--add-file /dev` but it stops aisap command to run at all

**Comment by mgord9518** [comment]
I'm gonna close this if everything is working. but feel free to re-open if you have other issues

Once I get some more time with my development machine I'll do a little testing and change all web browsers to level 1 so they should work without any tweaking
