### ISSUE TITLE
[+] Include aarch64 Builds

### ISSUE THREAD

**Issue by Azathothas** [mgord9518/aisap#17]
Hi, I looked at your https://github.com/mgord9518/aisap/blob/main/resources/build.sh, but it seems like it's assuming an x86_64 sysem as host.
Is it possible to have a build.sh that can be run on `aarch64` to produce `aarch64` binaries?

**Comment by mgord9518** [comment]
There is a shImg release with aarch64+x86_64, but at the time I couldn't figure out how to make a normal ARM AppImage. I'll have to completely re-do the build script, which should make it a lot easier to add release binaries and make it host-agnostic
