### ISSUE TITLE
[+] Broken Go Build

### ISSUE THREAD

**Issue by Azathothas** [mgord9518/aisap#18]
Hi, I created https://github.com/mgord9518/aisap/issues/17, and today I had some free time and wanted to see if I can build it myself from scratch. I tried to do it first on x86_64
I followed the build.sh instructions, https://github.com/mgord9518/aisap/blob/main/resources/build.sh
But I got:
```bash
github.com/mgord9518/aisap/spooky
github.com/mgord9518/aisap/permissions
# github.com/mgord9518/aisap/spooky
../../spooky/isspooky.go:4:2: "encoding/json" imported and not used
../../spooky/isspooky.go:21:1: missing return
github.com/mgord9518/aisap/profiles
github.com/mgord9518/aisap
```

I wonder if that only affects me (I have a crooked go env setup), anyways, I fixed it by:
```diff
#Removed "encoding/json" from line 4
 import (
- 	"encoding/json"
 	"strings"

#Added a tempp return at line 20 to avoid the "missing return" error
func isSpookyNew(path string) bool {
+ 	return false
}
```

```bash
$ du -sh aisap && file aisap
4.3M    aisap
aisap: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped

$ aisap --version
v0.10.2-alpha
```

**Comment by Azathothas** [comment]
It seems like @xplshn also ran into this:
https://github.com/mgord9518/aisap/compare/main...xplshn:aisap:main
![image](https://github.com/user-attachments/assets/816d5c3d-c45b-4299-97c1-13e4dcf14f6f)

**Comment by xplshn** [comment]
Fixed on my repo, switched to vendored

**Comment by mgord9518** [comment]
@xplshn Looks like you're doing really good work in your repo, would you like to push your changes upstream?

**Comment by xplshn** [comment]
Hi, good (pick yours: evening, afternoon, morning, noon), I very much would, but I don't think a PR would be that easy because I forked various repos and then changed everything to point to those instead, since I was having problems and wanted a bit more freedom to change stuff. You can probably still add this upstream tho!

Anyways, just to give you a heads up; I am working on Chains, mostly a rewrite of AISAP's Go version, will probably become a PR here replacing the entirety of the Go AISAP implementation if I can get it to a decent state, it does take lots of code here, but I am trying to use as most of the STD as possible, and I am trying to follow a procedural paradigm, so that the code remains readable.

:)

**Comment by Samueru-sama** [comment]
@mgord9518 I can try to PR the changes made to `wrap.go` and `helpers.go` since that's the biggest change and it fixes the hardcoded env vars issue. 

Although the CI will still be failing.

**Comment by mgord9518** [comment]
@xplshn That sounds awesome! I'd love to collaborate to ensure compatibility between our versions (permission implementation, profiles, etc). I've been trying to transition to storing most of everything in JSON but the progress has been slow. As long as we agree on the formatting it should be fairly easy to keep things in sync though

@Samueru-sama Thanks! I'll see if I can re-write the build script (probably into a Makefile?) in the next week or so

**Comment by xplshn** [comment]
> @xplshn That sounds awesome! I'd love to collaborate to ensure compatibility between our versions (permission implementation, profiles, etc). I've been trying to transition to storing most of everything in JSON but the progress has been slow. As long as we agree on the formatting it should be fairly easy to keep things in sync though

Yeah, it seems like you're moving to Zig, so I wanted to eventually apply to maintain the Go version of AISAP, which for now I'm locally calling `chains`.
I discussed with Samu about using .json for permissions earlier, but we agree that having them in the .desktop will be easier for appdir maintainers, if you want to reach out to me, I'm on Telegram, and @Azathothas, @Samueru-sama and I are working collaboratively on projects related to having portable Linux binaries, you can join and discuss these kinds of things if you'd like :)

This is my Telegram handle btw: xplshn_2008

**Comment by mgord9518** [comment]
@xplshn Unfortunately I don't have Telegram but I have Matrix and Discord if either work (or even just opening a discussion here on Github)

I think desktop files are the way to go for embedding into AppImages, JSON would just be for the internal profile library (which would only be edited by maintainers) and either compiled or embedded directly into the aisap binary.

**Comment by mgord9518** [comment]
I've started a discussion [here](https://github.com/mgord9518/aisap/discussions/19#discussion-7298462)

**Comment by Azathothas** [comment]
Hi @mgord9518 , for the go version, which you don't intend to maintain,
Fixing the isspooky.go would be much appreciated as it's the only thing that's breaking the go build.

For the zig version, you say it's not ready yet, so I will default to building the go version for now.
I have also resolved https://github.com/mgord9518/aisap/issues/17 , but I am leaving it open in case you yourself want to include aarch64 builds 

There's a matrix space at : https://matrix.to/#/%23official-loonix:matrix.org
But it's abandoned, because everyone wanted bigger file uploads and simplicity, which telegram offered.... (because Appimages...)

If you are still working on appimages or related formats, it would be worth it to join the telegram channel at: https://t.me/official_loonix/63949
We have big plans for appimages, & portable formats in general. 
There's a hope we can have a centralized repo (with transparent build process, logs and verification), that will have all the appimages, and other portable formats, similar to my previous work over at: https://github.com/Azathothas/Toolpacks
And to offer it all for free, and with predictable endpoints and metadata so anyone or any package managers, can use it.
If all of that sounds exciting, please join us in the discussions, it would be very helpful.
Thanks!

**Comment by xplshn** [comment]
Btw, I'm making progress with restructuring AISAP and migrating to using the official goappimage library at https://github.com/xplshn/chains :)
We can probably re-organize this repo into two separate folders, one with the Go implementation and one containing the Zig one, and the docs which shall be on the top level. Just leaving it out there, could probably PR all of the changes once I am done :)

**Comment by mgord9518** [comment]
@xplshn That sounds perfect!

**Comment by xplshn** [comment]
I'm not sure if I'll ever actually finish it, currently I'm working on other projects. Such as the new AppBundleHUB and its webpage, as well as on the PELF tooling which is used to generate .AppBundles

**Comment by ivan-hc** [comment]
> [@xplshn](https://github.com/xplshn) Unfortunately I don't have Telegram but I have Matrix and Discord if either work (or even just opening a discussion here on Github)


@mgord9518 please join https://discord.com/channels/1313385177703256064/1313398899116867585 so we can keep talking about this on Discord, since you have an account

**Comment by mgord9518** [comment]
@ivan-hc I got an error saying there are no text channels on the server

**Comment by Samueru-sama** [comment]
> [@ivan-hc](https://github.com/ivan-hc) I got an error saying there are no text channels on the server

Can you try the discord link here? https://docs.pkgforge.dev/contact/chat

**Comment by ivan-hc** [comment]
> [@ivan-hc](https://github.com/ivan-hc) I got an error saying there are no text channels on the server

@mgord9518 Sorry, I'm not familiar with how to share an invite on Discord 🤦 

Thanks @Samueru-sama
