### ISSUE TITLE
Have apps request the needed permissions

### ISSUE THREAD

**Issue by probonopd** [mgord9518/aisap#3]
Hello @mgord9518, very interesting project. In fact, this is one of the missing pieces for sandboxing support in https://github.com/probonopd/go-appimage.

> The ultimate goal is to have as many AppImages in [aisap's internal library](https://github.com/mgord9518/aisap/blob/main/profiles/README.md) as possible, while smaller, less known apps may request their own permssions per the developer. Running programs sandboxed should mostly be seamless and feel native with the system

Why not have applications request the needed permissions, so that upon the first launch of the application the user could be asked whether to accept or change the permissions requested by the application? Something along those lines.
This way, aisap's internal library would not need to know about any particular AppImages (which I think could be tricked rather easily anyway).

**Comment by mgord9518** [comment]
@probonopd That's the exact thing I had in mind when I started creating aisap, but I think it's outside the scope of the CLI tool (which is mostly just intended to be an example implementation or embedded tool in more advanced software).

A simple GUI program that uses aisap could check the permissions, then display them in a list, allowing a user to add or remove from them before launching the application is what I imagine.

I was actually working on a mockup for such an application in Go and FLTK but put it on the back burner as I'm juggling quite a few active projects currently

**Comment by probonopd** [comment]
Thing is, FLTK looks alien everywhere... as a start, we could simply enforce whatever the app specifies.

**Comment by mgord9518** [comment]
@probonopd Yeah, that'd probably be the way to go with go-appimage.

As for FLTK, it amazes me how "native" an application can look just from using the system's colors correctly. [Here](https://raw.githubusercontent.com/mgord9518/images/main/fltk.avif) is an image of a file manager I had started working on a while ago with FLTK. Unfortunately for the file manager itself, the codebase will have to be re-written as Go is a royal pain to use along something with manual memory management in mind like FLTK so I'm gonna use Zig, but it looks pretty integrated as an example imo. Of course, it'll never look as perfect as a Qt app on a Qt system or a GTK app on a GTK system, but I think it looks a lot better than something like a CSD GTK app on KDE.

**Comment by mgord9518** [comment]
@probonopd I've been thinking about this some more, maybe aisap can have a config of trusted AppImages according to the user that can be read with an API? Then anything using it can use these APIs to check and warn the user, I suppose it wouldn't hurt anything to add it to the CLI tool either

Example:
```
*AppImage.IsTrusted() bool
*AppImage.SetTrusted(bool)
```

And an example of how this may work in the CLI tool:
```
./aisap untrusted.AppImage
warning: this bundle hasn't been run yet and is currently untrusted.
would you like to (r)un once, (t)rust permanently and run or (c)ancel?
[r/t/c]:
```

**Comment by probonopd** [comment]
Isn't that what the execute bit (`chmod +x`) is for? Let's not store the same kind of information in yet another place.

**Comment by mgord9518** [comment]
@probonopd I suppose so, but that can't be used on say a FAT USB drive, which is something I personally do with AppImages sometimes and I believe it's not an uncommon practice.

**Comment by probonopd** [comment]
FAT USB drives need to be mounted without `noexec` and without `showexec`.

Unfortunately UDisks still defaults to using `showexec` which I find extremely annoying.
At least they have made it configurable somehow:

* https://github.com/storaged-project/udisks/issues/707

**Comment by mgord9518** [comment]
@probonopd I've always thought some sort of metafile should be used to store Linux permissions on filesystems that don't support them. Obviously it's not realistic as it would have to be in the kernel and I assume a lot of users wouldn't like defaulting to some extra file trashing up their thumb drives

I think another possible issue with using the exec flag for this is that any malicious program could just come packaged in a zip or tar with it on and be automatically trusted. AppImages *shouldn't* come packaged like this, but some already do

**Comment by probonopd** [comment]
> I think another possible issue with using the exec flag for this is that any malicious program could just come packaged in a zip or tar with it on and be automatically trusted

That's not AppImage specific. The same applies for all sorts of scripts and binaries.

**Comment by mgord9518** [comment]
@probonopd I'm not saying it's an AppImage-only problem, I'm just saying that it shouldn't be used for trusting an application in a security context

**Comment by mgord9518** [comment]
Added in https://github.com/mgord9518/aisap/commit/04950ac036ba8223a1776d590e8e2fb6f59055da
